import Head from "next/head";
import useSWR from "swr";
import axios from "axios";
import { Poppins, Oswald } from "@next/font/google";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  FaTwitterSquare,
  FaLinkedin,
  FaGithubSquare,
  FaCopyright,
} from "react-icons/fa";
import { MdEmail } from "react-icons/md";
// import NavSlider from "@/components/NavSlider";
import ProjectCard from "@/components/ProjectCard";
import Loader from "@/components/Loader";
const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  style: "normal",
  subsets: ["latin"],
});
const oswald = Oswald({
  weight: ["200", "400", "500", "600", "700"],
  style: "normal",
  subsets: ["latin"],
});
const fetcher = (url: string) => axios.get(url).then((res) => res.data);
export default function Home() {
  const route = useRouter().asPath;
  const { data, error, isLoading } = useSWR("/api/projects", fetcher);
  console.log(data);

  return (
    <>
      <Head>
        <title>Folorunsho Ibrahim Portolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={`${oswald.className} md:px-12 lg:px-20`}>
        <div
          aria-label="Website Logo and Social Links"
          className="flex items-center justify-between p-4 md:px-0"
        >
          <h1 className={`${poppins.className} font-bold text-lg`}>Fibr</h1>
          <ul className="flex items-center gap-4">
            <Link
              className="flex gap-2 items-center "
              href="mailto:tacheyontech@gmail.com"
              target="_blank"
            >
              <li>
                <MdEmail className="text-3xl text-white hover:text-purple-500 transition duration-300" />
              </li>
            </Link>

            <li>
              <Link
                className="flex gap-2 items-center"
                href="https://www.linkedin.com/in/folorunsho-ibrahim-t/"
                target="_blank"
              >
                <FaLinkedin className="text-2xl text-white hover:text-purple-500 transition duration-300" />
              </Link>
            </li>
            <li>
              <Link
                className="flex gap-2 items-center"
                href="https://twitter.com/tacheyontechs"
                target="_blank"
              >
                <FaTwitterSquare className="text-2xl text-white hover:text-purple-500 transition duration-300" />
              </Link>
            </li>
            <li>
              <Link
                className="flex gap-2 items-center"
                href="https://github.com/folorunsho-tech"
                target="_blank"
              >
                <FaGithubSquare className="text-2xl text-white hover:text-purple-500 transition duration-300" />
              </Link>
            </li>
          </ul>
        </div>
        <ul className="flex items-center gap-4 py-2 text-lg px-4 md:px-0">
          <li
            className={
              route == "/#projects"
                ? "border-b border-b-purple-700 pb-1 "
                : "border-b border-b-transparent pb-1 hover:border-b-purple-500 transition duration-150"
            }
          >
            <Link href="#projects">Projects</Link>
          </li>
          <li
            className={
              route == "/#blog"
                ? "border-b border-b-purple-700 pb-1 "
                : "border-b border-b-transparent pb-1 hover:border-b-purple-500 transition duration-150"
            }
          >
            <Link href="#blog">Blog</Link>
          </li>
          {/* <li className={route=='/#projects'?'border-b border-b-purple-700 pb-1':'border-b border-b-transparent pb-1'}><Link href='#about-me'>About Me</Link>/li> */}
          <li
            className={
              route == "/#contact-me"
                ? "border-b border-b-purple-700 pb-1 "
                : "border-b border-b-transparent pb-1 hover:border-b-purple-500 transition duration-150"
            }
          >
            <Link href="#contact-me">Contact Me</Link>
          </li>
        </ul>
      </nav>
      <header
        className={`${poppins.className} p-4 space-y-4 md:space-y-6 md:px-12 lg:px-20 `}
      >
        <h2 className="text-3xl md:text-5xl leading-loose ">
          Nice to meet you!, I'm{" "}
          <span className="font-semibold border-b border-b-purple-600 hover:border-b-purple-400 transition duration-150">
            Folorunsho Ibrahim
          </span>
        </h2>
        <p className={`${oswald.className} text-lg md:text-xl max-w-lg`}>
          Based in New Bussa, Nigeria. I'm a Software Engineer, I build
          efficient, scalable and straight-to-the-point softwares that users
          love.
        </p>
        <p>
          <Link
            href="#contact-me"
            className=" pb-1 border-b-4 border-b-purple-700 hover:border-b-purple-500 transition duration-150"
          >
            Contact Me
          </Link>
        </p>
      </header>
      <main className={`${poppins.className} p-4 space-y-4 md:px-12 lg:px-20`}>
        <h2 className="text-2xl">Projects</h2>
        {/* <NavSlider /> */}
        <hr className="border-purple-400" />
        <section
          className="md:grid md:grid-cols-2 md:gap-6 flex flex-col gap-8"
          id="projects"
        >
          {isLoading && (
            <>
              <Loader />
              <Loader />
              <Loader />
              <Loader />
              <Loader />
              <Loader />
            </>
          )}
          {!isLoading &&
            data[0].projects?.map((project: any) => (
              <ProjectCard
                key={project?.name}
                {...project}
                category={data[0].category}
              />
            ))}
        </section>
      </main>
      <footer
        className={`${oswald.className} space-y-3 p-4 mt-12 md:px-12 lg:px-20`}
      >
        <h2 className={`${poppins.className} text-2xl`}>Contact Me</h2>
        <hr className="border-purple-400 pb-4" />
        <ul className="space-y-4 " id="contact-me">
          <li>
            <Link
              className="flex gap-2 items-center"
              href="mailto:tacheyontech@gmail.com"
              target="_blank"
            >
              <MdEmail className="text-2xl text-white" />
              <span className="border-b border-b-purple-700 pb-1 hover:border-b-purple-500 transition duration-150">
                tacheyontech@gmail.com
              </span>
            </Link>
          </li>
          <li>
            <Link
              className="flex gap-2 items-center"
              href="https://www.linkedin.com/in/folorunsho-ibrahim-t/"
              target="_blank"
            >
              <FaLinkedin className="text-2xl text-white" />
              <span className="border-b border-b-purple-700 pb-1 hover:border-b-purple-500 transition duration-150">
                Folorunsho Ibrahim
              </span>
            </Link>
          </li>
          <li>
            <Link
              className="flex gap-2 items-center"
              href="https://twitter.com/tacheyontechs"
              target="_blank"
            >
              <FaTwitterSquare className="text-2xl text-white" />
              <span className="border-b border-b-purple-700 pb-1 hover:border-b-purple-500 transition duration-150">
                @tacheyontechs
              </span>
            </Link>
          </li>
          <li>
            <Link
              className="flex gap-2 items-center"
              href="https://github.com/folorunsho-tech"
              target="_blank"
            >
              <FaGithubSquare className="text-2xl text-white" />
              <span className="border-b border-b-purple-700 pb-1 hover:border-b-purple-500 transition duration-150">
                folorunsho-tech
              </span>
            </Link>
          </li>
        </ul>
        <hr className="border-purple-400" />
        <div
          className={`${poppins.className} flex items-center justify-between`}
        >
          <h2 className={`text-4xl`}>Fibr</h2>
          <h2 className={`text-xl flex items-center gap-3`}>
            <FaCopyright className="text-2xl" /> 2023
          </h2>
        </div>
      </footer>
    </>
  );
}
